package com.capacidad.validationapi.module.premedicalauthorization.service.impl;

import com.capacidad.utils.exception.ObjectNotFoundException;
import com.capacidad.validationapi.misc.Utils;
import com.capacidad.validationapi.module.beneficiary.model.Beneficiary;
import com.capacidad.validationapi.module.beneficiary.service.BeneficiaryFinder;
import com.capacidad.validationapi.module.general.model.Status;
import com.capacidad.validationapi.module.nomenclator.model.Nomenclator;
import com.capacidad.validationapi.module.nomenclator.service.NomenclatorService;
import com.capacidad.validationapi.module.person.model.IdType;
import com.capacidad.validationapi.module.person.reference.IdTypeReference;
import com.capacidad.validationapi.module.practitioner.model.Practitioner;
import com.capacidad.validationapi.module.practitioner.service.PractitionerService;
import com.capacidad.validationapi.module.premedicalauthorization.dto.BasePreMedicalAuthorizationDTO;
import com.capacidad.validationapi.module.premedicalauthorization.dto.PreMedicalAuthorizationDTO;
import com.capacidad.validationapi.module.premedicalauthorization.dto.PrePopulatedPreMedicalAuthorizationDTO;
import com.capacidad.validationapi.module.premedicalauthorization.model.PreMedicalAuthorization;
import com.capacidad.validationapi.module.premedicalauthorization.model.PreMedicalAuthorizationItem;
import com.capacidad.validationapi.module.premedicalauthorization.service.PreMedicalAuthorizationBuilder;
import com.capacidad.validationapi.module.properties.model.Properties;
import com.capacidad.validationapi.module.properties.service.PropertiesService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.hashids.Hashids;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.LocalDate;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

import static com.capacidad.validationapi.functional.ThrowingFunction.throwingFunction;
import static com.capacidad.validationapi.module.general.reference.StatusReference.PRE_MEDICAL_AUTHORIZATION_ACTIVE;

@Component
public class PreMedicalAuthorizationBuilderImpl implements PreMedicalAuthorizationBuilder {

    private final PractitionerService practitionerService;
    private final BeneficiaryFinder beneficiaryFinder;
    private final NomenclatorService nomenclatorService;
    private final PropertiesService propertiesService;
    private final ObjectMapper objectMapper;
    private final Hashids hashids;
    private final Utils utils;

    public PreMedicalAuthorizationBuilderImpl(PractitionerService practitionerService,
                                              BeneficiaryFinder beneficiaryFinder,
                                              NomenclatorService nomenclatorService,
                                              PropertiesService propertiesService,
                                              ObjectMapper objectMapper,
                                              @Qualifier("reducedHashids") Hashids hashids,
                                              Utils utils) {
        this.practitionerService = practitionerService;
        this.beneficiaryFinder = beneficiaryFinder;
        this.nomenclatorService = nomenclatorService;
        this.propertiesService = propertiesService;
        this.objectMapper = objectMapper;
        this.hashids = hashids;
        this.utils = utils;
    }

    @Override
    public <P extends BasePreMedicalAuthorizationDTO> PreMedicalAuthorization build(P dto) throws ObjectNotFoundException {
        if (dto instanceof PreMedicalAuthorizationDTO)
            return buildRegular((PreMedicalAuthorizationDTO) dto);
        return buildPrePopulated((PrePopulatedPreMedicalAuthorizationDTO) dto);
    }

    private PreMedicalAuthorization buildRegular(PreMedicalAuthorizationDTO dto) {
        PreMedicalAuthorization object = objectMapper.convertValue(dto, PreMedicalAuthorization.class);
        setProperties(object);
        object.associateChildObjects();
        return object;
    }

    private void setProperties(PreMedicalAuthorization object) {
        Properties props = propertiesService.getProperties();
        object.setExpirationDate(LocalDate.now().plusDays(props.getPreAuthorizationMaxDays()));
        object.setCode(buildCode());
        Status active = utils.getGenericsEntityReference(Status.class, PRE_MEDICAL_AUTHORIZATION_ACTIVE.getId());
        object.setStatus(active);
        setRemainingItems(object);
    }

    /**
     * PreMedicalAuthorization key code
     * Timestamp is multiplied by fixed constant to avoid hashing that single value only.
     * Avoid sum of timestamp with varying constants like IDs to avoid collisions
     * generated by raise conditions.
     */
    private String buildCode() {
        long code = Instant.now().toEpochMilli() * 2;
        return hashids.encode(code);
    }


    private PreMedicalAuthorization buildPrePopulated(PrePopulatedPreMedicalAuthorizationDTO dto) throws ObjectNotFoundException {
        PreMedicalAuthorization object = new PreMedicalAuthorization();
        resolvePetitioner(dto).ifPresent(object::setPetitioner);
        Beneficiary beneficiary = beneficiaryFinder.findBeneficiary(dto.getBeneficiaryCode());
        object.setBeneficiary(beneficiary);
        Set<PreMedicalAuthorizationItem> items = buildPreMedicalAuthorizationItems(dto);
        object.setPreMedicalAuthorizationItems(items);
        setProperties(object);
        object.associateChildObjects();
        return object;
    }

    private Optional<Practitioner> resolvePetitioner(PrePopulatedPreMedicalAuthorizationDTO dto) {
        Long petitionerIdNumber = dto.getPetitionerIdNumber();
        if (petitionerIdNumber != null) {
            IdType defaultIdType = new IdType();
            defaultIdType.setId(IdTypeReference.ID.getId());
            return practitionerService.findOptionallyByIdTypeAndIdNumber(defaultIdType, dto.getPetitionerIdNumber());
        }
        return Optional.empty();
    }

    private Set<PreMedicalAuthorizationItem> buildPreMedicalAuthorizationItems(PrePopulatedPreMedicalAuthorizationDTO dto) {
        return dto.getPreMedicalAuthorizationItems().stream()
                .map(throwingFunction(i -> {
                    PreMedicalAuthorizationItem preMedicalAuthorizationItem = new PreMedicalAuthorizationItem();
                    Nomenclator nomenclator = nomenclatorService.findByNomenclatorCode(i.getNomenclatorCode());
                    preMedicalAuthorizationItem.setNomenclator(nomenclator);
                    preMedicalAuthorizationItem.setChargeUnitPrice(i.getChargeUnitPrice());
                    preMedicalAuthorizationItem.setQuantity(i.getQuantity());
                    return preMedicalAuthorizationItem;
                }))
                .collect(Collectors.toUnmodifiableSet());
    }

    private void setRemainingItems(PreMedicalAuthorization preMedicalAuthorization) {
        preMedicalAuthorization.getPreMedicalAuthorizationItems().forEach(i -> i.setRemaining(i.getQuantity()));
    }

}
