#Datasource Properties
spring.datasource.jdbcUrl=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.initialization-mode=never
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.data=classpath:/data/*.sql,classpath:/data/*/*.sql
spring.datasource.hikari.maximum-pool-size=85
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=40000
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=256
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.socketTimeout=30
#JPA/Hibernate Properties
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=com.capacidad.validationapi.config.PGDialect
spring.jpa.hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
spring.jpa.hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#Server
server.servlet.context-path=/validation-api/v1
server.port=${PORT}
server.forward-headers-strategy=framework
#Task Executor
spring.task.execution.pool.core-size=15
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100
spring.task.execution.pool.keep-alive=60s
#Logging Properties
logging.level.com.capacidad.validationapi=info
logging.file.name=/shared/logs/validation-api.log
#Actuator
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=metrics,health,info,httptrace,env
management.endpoint.health.enabled=true
management.endpoint.health.show-details=when_authorized
management.health.db.enabled=false
management.endpoint.info.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.httptrace.enabled=true
management.endpoint.env.enabled=true
#i18n
spring.messages.basename=messages/messages
spring.messages.fallback-to-system-locale=false
spring.messages.encoding=UTF-8
spring.mvc.locale-resolver=accept_header
spring.mvc.locale=es
#Storage
com.capacidad.validationapi.storage.file-extensions=docx,doc,pdf,png,jpeg,jpg,txt
com.capacidad.validationapi.storage.file-signatures=1347093252,-791735840,626017350,-1991225785,-2555936,-2555935,-272646673,-272646832,1349678437
com.capacidad.validationapi.storage.s3.region=us-east-1
#Import
com.capacidad.validationapi.import-processor.file-extensions=csv
#Multipart Files Properties
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
com.capacidad.validationapi.rabbitmq.stomp.port=${RABBITMQ_STOMP_PORT}
#Flyway
spring.flyway.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.flyway.schemas=public
spring.flyway.user=${DATABASE_USERNAME}
spring.flyway.password=${DATABASE_PASSWORD}
spring.flyway.locations=classpath:migrations/${spring.profiles.active}
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true
#Quartz
spring.quartz.enabled=true
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.scheduler.instanceId=instanceOne
spring.quartz.properties.org.quartz.scheduler.instanceName=jobScheduler
spring.quartz.properties.org.quartz.threadPool.threadCount=10
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000
spring.quartz.properties.org.quartz.jobStore.tablePrefix=qrtz_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.plugin.shutdownHook.class=org.quartz.plugins.management.ShutdownHookPlugin
spring.quartz.properties.org.quartz.plugin.shutdownHook.cleanShutdown=TRUE
#Notification
com.capacidad.validationapi.notification-service.enabled=true
#Prescription
com.capacidad.validationapi.prescription-synchronization.enabled=true
#Custom Properties
com.capacidad.validationapi.identifier=W6ckIkHpT5uaI1TQSjcJTMu1cnIzHO

spring.profiles.active=dev

