#Galbop Datasource Properties
galbop.datasource.jdbcUrl=jdbc:mysql://${GALBOP_DATABASE_HOST}:${GALBOP_DATABASE_PORT}/${GALBOP_DATABASE_NAME}?reWriteBatchedInserts=true
galbop.datasource.username=${GALBOP_DATABASE_USERNAME}
galbop.datasource.password=${GALBOP_DATABASE_PASSWORD}
galbop.datasource.initialization-mode=never
galbop.datasource.driverClassName=com.mysql.jdbc.Driver
galbop.datasource.hikari.connection-timeout=50000
galbop.datasource.hikari.max-lifetime=900000
galbop.datasource.hikari.maximum-pool-size=125
galbop.datasource.hikari.minimum-idle=25
galbop.jpa.hibernate.hbm2ddl.auto=none
galbop.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
galbop.jpa.hibernate.order_updates=false
galbop.jpa.hibernate.batch_versioned_data=false