spring.config.activate.on-profile=dev

# Database
DATABASE_NAME=identityservice
DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=ramones16


#Datasource
#spring.datasource.url=jdbc:postgresql://localhost:5432/validationapitest
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization-mode=always
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=15

#JPA/Hibernate Properties
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=1500
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#server
server.port=${PORT:8080}

#Logging
logging.level.com.capacidad.identityservice=debug
logging.level.com.zaxxer.hikari.HikariConfig=debug
logging.level.com.zaxxer.hikari=trace
logging.level.org.springframework.security.oauth2.provider.token.store=error

# URL de OpenAPI
springdoc.api-docs.path=/identity-service/v1/api-docs

# URL de Swagger UI
springdoc.swagger-ui.path=/identity-service/v1/swagger-ui.html

spring.flyway.enabled=false


#  todo -> en produccion , definir esta clave en una variable de entorno !!
OTP_KEY=dev-secret-123

# todo -> en produccion , definir este host
NOTIFICATION_SERVICE_HOST=http://localhost:8081

# mock
NOTIFICATION_SERVICE_CLIENT_ID=dev-client-id
NOTIFICATION_SERVICE_SECRET=secret123456


#todo , revisar las vars de entorno de redis !!
#Redis
spring.redis.cluster.nodes=${REDIS_NODES}
spring.redis.cluster.max-redirects=3
spring.redis.lettuce.pool.min-idle=50
spring.redis.lettuce.pool.max-idle=150
spring.redis.lettuce.pool.max-active=350
spring.redis.lettuce.pool.max-wait=5000
spring.redis.timeout=3500ms