spring.config.activate.on-profile=dev

# Database vps nahuel
#DATABASE_NAME=login
#DATABASE_HOST=168.181.187.5
#DATABASE_PORT=3306
#DATABASE_USERNAME=nahuel
#DATABASE_PASSWORD=prueba1234

# Database
DATABASE_NAME=identityservice
DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=ramones16

#DATABASE_PORT=3306
# DATABASE_PORT=5432 postgres

#Datasource
#spring.datasource.url=jdbc:mysql://168.181.187.5:3306/ipross?
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

useSSL=false&serverTimezone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.initialization-mode=always
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=15

#JPA/Hibernate Properties
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update , se han cargado de forma manual las tablas de los modelos !!
spring.jpa.show-sql=true
spring.jpa.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=1500
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=none


#server
server.port=${PORT:8080}

#Logging
logging.level.com.capacidad.identityservice=debug
logging.level.com.zaxxer.hikari.HikariConfig=debug
logging.level.com.zaxxer.hikari=trace
logging.level.org.springframework.security.oauth2.provider.token.store=error


#se requiere tener acceso de usuario para ver los endpoints en swagger,
# JSON de OpenAPI
springdoc.api-docs.path=/identity-service/v1/api-docs
# Swagger UI path
springdoc.swagger-ui.path=/identity-service/v1/swagger-ui

#swagger
springdoc.swagger-ui.oauth.client-id=mi-client-id
springdoc.swagger-ui.oauth.client-secret=mi-client-secret
springdoc.swagger-ui.oauth.realm=mi-realm
springdoc.swagger-ui.oauth.app-name=identity-service
springdoc.swagger-ui.oauth.scopes=read,write

#flyway , desactivado , he creado en local las tablas de las entidades de este proyecto
spring.flyway.enabled=false


jwt.secret=a7bc9c2ee804b92d4ec81491cb4710a86c9118b98d102a6cd0ca5f065b317c61


#  todo -> en produccion , definir esta clave en una variable de entorno !!
OTP_KEY=dev-secret-123

# todo -> en produccion , definir este host
NOTIFICATION_SERVICE_HOST=http://localhost:8081

# mock notification service
NOTIFICATION_SERVICE_CLIENT_ID=dev-client-id
NOTIFICATION_SERVICE_SECRET=secret123456


#todo , revisar las vars de entorno de redis !!
#Redis
REDIS_NODES=localhost:6379
spring.redis.cluster.max-redirects=3
