#Datasource
spring.datasource.initialization-mode=always
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=15
#JPA/Hibernate Properties
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=1500
#Task Executor
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=15
spring.task.execution.pool.queue-capacity=100
#Logging
logging.level.com.capacidad.validationapi=debug
logging.level.com.zaxxer.hikari.HikariConfig=debug
logging.level.com.zaxxer.hikari=trace
#Notification
com.capacidad.validationapi.notification-service.enabled=true
#Prescription
com.capacidad.validationapi.prescription-synchronization.enabled=false
#Flyway
spring.flyway.baseline-version=1.1.29