//PROFILES

export const FETCHING_USER_DATA = 'FETCHING_USER_DATA';
export const USER_DATA_FETCHED = 'USER_DATA_FETCHED';

export const LOGGED_IN = 'LOGGED_IN';

export const LOGGING_IN = 'LOGGING_IN';

export const CONFIRMING_TEMPORARY_PASSWORD = 'CONFIRMING_TEMPORARY_PASSWORD';
export const RENEW_PASSWORD = 'RENEW_PASSWORD';

export const ACCOUNT_CREATED = 'ACCOUNT_CREATED';
export const CREATING_ACCOUNT = 'CREATING_ACCOUNT';

export const LOGGED_OUT = 'LOGGED_OUT';

export const FETCH_RELATIVES_SUCCESS = 'FETCH_RELATIVES_SUCCESS';
export const FETCHING_RELATIVES = 'FETCHING_RELATIVES';

export const VALIDATING_DATA = 'VALIDATING_DATA';
export const VALIDATION_DATA_SUCCESS = 'VALIDATION_DATA_SUCCESS';
export const VALIDATION_DATA_ERROR = 'VALIDATION_DATA_ERROR';
export const CLEAR_VALIDATION_ERROR = 'CLEAR_VALIDATION_ERROR';

export const CONFIRMING_PASSWORD_FORGOT_PASSWORD = 'CONFIRMING_PASSWORD_FORGOT_PASSWORD';
export const CONFIRM_PASSWORD_FORGOT_PASSWORD_SUCCESS = 'CONFIRM_PASSWORD_FORGOT_PASSWORD_SUCCESS';

export const CHANGE_USER = 'CHANGE_USER';

export const UPDATING_SELECTED_USER_DATA = 'UPDATING_SELECTED_USER_DATA';
export const SELECTED_USER_DATA_UPDATED = 'SELECTED_USER_DATA_UPDATED';

export const UPDATE_TEMPORARY_PASSWORD_SUCCESS = 'UPDATE_TEMPORARY_PASSWORD_SUCCESS';
export const SENDING_OTP_EMAIL = 'SENDING_OTP_EMAIL';
export const SEND_OTP_EMAIL_SUCCESS = 'SEND_OTP_EMAIL_SUCCESS';
export const USER_DEVICE_REGISTED = 'USER_DEVICE_REGISTED';

//ROUTER

export const UPDATING_CURRENT_SCENE = 'UPDATING_CURRENT_SCENE';

//VALIDATIONS

export const FETCHING_VALIDATIONS = 'FETCHING_VALIDATIONS';
export const FETCH_VALIDATIONS_SUCCESS = 'FETCH_VALIDATIONS_SUCCESS';
export const FETCHING_MORE_VALIDATIONS = 'FETCHING_MORE_VALIDATIONS';
export const FETCH_MORE_VALIDATION_SUCCESS = 'FETCH_MORE_VALIDATION_SUCCESS';
export const SELECT_VALIDATION = 'SELECT_VALIDATION';
export const FETCHING_VALIDATION_ASSOCIATED_FILES = 'FETCHING_VALIDATION_ASSOCIATED_FILES';
export const FETCH_VALIDATION_ASSOCIATED_FILES_SUCCESS = 'FETCH_VALIDATION_ASSOCIATED_FILES_SUCCESS';
export const FETCHING_VALIDATION = 'FETCHING_VALIDATION';
export const FETCH_VALIDATION_SUCCESS = 'FETCH_VALIDATION_SUCCESS';
export const RANKED_AUTHORIZATION_SUCCESS = 'RANKED_AUTHORIZATION_SUCCESS';
export const FETCHING_PREAUTHORIZATIONS = 'FETCHING_PREAUTHORIZATIONS';
export const FETCHING_MORE_PREAUTHORIZATIONS = 'FETCHING_MORE_PREAUTHORIZATIONS';
export const FETCH_MORE_PREAUTHORIZATIONS_SUCCESS = 'FETCH_MORE_PREAUTHORIZATIONS_SUCCESS';
export const FETCH_PREAUTHORIZATIONS_SUCCESS = 'FETCH_PREAUTHORIZATIONS_SUCCESS';
export const FETCHING_PREAUTHORIZATION = 'FETCHING_PREAUTHORIZATION';
export const FETCH_PREAUTHORIZATION_SUCCESS = 'FETCH_PREAUTHORIZATION_SUCCESS';

//CHARGES

export const FETCHING_CHARGES = 'FETCHING_CHARGES';
export const FETCH_CHARGES_SUCCESS = 'FETCH_CHARGES_SUCCESS';
export const CLEAR_CHARGES_STATUS = 'CLEAR_CHARGES_STATUS';
export const FETCH_MORE_CHARGES_SUCCESS = 'FETCH_MORE_CHARGES_SUCCESS';
export const FETCHING_MORE_CHARGES = 'FETCHING_MORE_CHARGES';

//ERRORS

export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ERROR_REPORTERED = 'ERROR_REPORTERED';

//BATCHES
export const FETCHING_BATCH = 'FETCHING_BATCH';
export const FETCH_BATCH_SUCCESS = 'FETCH_BATCH_SUCCESS';
export const FETCHING_BATCHES = 'FETCHING_BATCHES';
export const FETCH_BATCHES_SUCCESS = 'FETCH_BATCHES_SUCCESS';
export const FETCHING_MORE_BATCHES = 'FETCHING_MORE_BATCHES';
export const FETCH_MORE_BATCHES_SUCCESS = 'FETCH_MORE_BATCHES_SUCCESS';
export const FETCHING_BATCH_ITEMS = 'FETCHING_BATCH_ITEMS';
export const FETCH_BATCH_ITEMS_SUCCESS = 'FETCH_BATCH_ITEMS_SUCCESS';
export const FETCHING_MORE_BATCH_ITEMS = 'FETCHING_MORE_BATCH_ITEMS';
export const FETCH_MORE_BATCH_ITEMS_SUCCESS = 'FETCH_MORE_BATCH_ITEMS_SUCCESS';

//TRIPS
export const FETCHING_TRIPS = 'FETCHING_TRIPS';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';

//PROCEDURES
export const FETCHING_PROCEDURES = 'FETCHING_PROCEDURES';
export const FETCH_PROCEDURES_SUCCESS = 'FETCH_PROCEDURES_SUCCESS';
export const FETCHING_CERTIFICATE_TYPES = 'FETCHING_CERTIFICATE_TYPES';
export const FETCH_CERTIFICATE_TYPES_SUCCESS = 'FETCH_CERTIFICATE_TYPES_SUCCESS';
export const CREATING_PROCEDURE = 'CREATING_PROCEDURE';
export const CREATE_PROCEDURE_SUCCESS = 'CREATE_PROCEDURE_SUCCESS';
export const FETCHING_PROCEDURE_BY_ID = 'FETCHING_PROCEDURE_BY_ID';
export const FETCH_PROCEDURE_BY_ID_SUCCESS = 'FETCH_PROCEDURE_BY_ID_SUCCESS';
export const UPDATING_PROCEDURE = 'UPDATING_PROCEDURE';
export const UPDATE_PROCEDURE_SUCCESS = 'UPDATE_PROCEDURE_SUCCESS';
export const ADDING_MESSAGE_TO_PROCEDURE = 'ADDING_MESSAGE_TO_PROCEDURE';
export const ADD_MESSAGE_TO_PROCEDURE_SUCCESS = 'ADD_MESSAGE_TO_PROCEDURE_SUCCESS';
export const FETCHING_SELECTED_PROCEDURE_MESSAGES = 'FETCHING_SELECTED_PROCEDURE_MESSAGES';
export const FETCH_SELECTED_PROCEDURE_MESSAGES_SUCCESS = 'FETCH_SELECTED_PROCEDURE_MESSAGES_SUCCESS';
export const FETCHING_MORE_PROCEDURES = 'FETCHING_MORE_PROCEDURES';
export const FETCH_MORE_PROCEDURES_SUCCESS = 'FETCH_MORE_PROCEDURES_SUCCESS';
export const FETCH_AUTHORIZATION_PROCEDURE_SUCCESS = 'FETCH_AUTHORIZATION_PROCEDURE_SUCCESS';

//PRESCRIPTION
export const FETCHING_PRESCRIPTIONS = 'FETCHING_PRESCRIPTIONS';
export const FETCH_PRESCRIPTIONS_SUCCESS = 'FETCH_PRESCRIPTIONS_SUCCESS';
export const FETCHING_MORE_PRESCRIPTIONS = 'FETCHING_MORE_PRESCRIPTIONS';
export const FETCH_MORE_PRESCRIPTIONS_SUCCESS = 'FETCH_MORE_PRESCRIPTIONS_SUCCESS';
export const SELECT_PRESCRIPTION = 'SELECT_PRESCRIPTION';
export const FETCHING_PRESCRIPTION = 'FETCHING_PRESCRIPTION';
export const FETCH_PRESCRIPTION_SUCCESS = 'FETCH_PRESCRIPTION_SUCCESS';

//APPOINTMENTS (TURNOS)

export const APPOINTMENT_LOGGED_IN = 'APPOINTMENT_LOGGED_IN';
export const APPOINTMENT_LOGGING_IN = 'APPOINTMENT_LOGGING_IN';
export const FETCHING_APPOINTMENTS = 'FETCHING_APPOINTMENTS';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const APPLICANTS_REGISTER = 'APPLICANTS_REGISTER';
export const FETCHING_APPLICANT = 'FETCHING_APPLICANT';
export const FETCH_APPLICANT_SUCCESS = 'FETCH_APPLICANT_SUCCESS';
export const FETCHING_DELEGATIONS = 'FETCHING_DELEGATIONS';
export const FETCH_DELEGATIONS_SUCCESS = 'FETCH_DELEGATIONS_SUCCESS';
export const FETCHING_SECTORS = 'FETCHING_SECTORS';
export const FETCH_SECTORS_SUCCESS = 'FETCH_SECTORS_SUCCESS';
export const FETCHING_APPOINTMENTS_ENABLED = 'FETCHING_APPOINTMENTS_ENABLED';
export const FETCH_APPOINTMENTS_ENABLED_SUCCESS = 'FETCH_APPOINTMENTS_ENABLED_SUCCESS';
export const APPOINTMENT_CREATE = 'APPOINTMENT_CREATE';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const APPOINTMENT_CONFIRM = 'APPOINTMENT_CONFIRM';
export const APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL';
export const FETCHING_APPOINTMENT_BY_ID = 'FETCHING_APPOINTMENT_BY_ID';
export const FETCH_APPOINTMENT_BY_ID_SUCCESS = 'FETCH_APPOINTMENT_BY_ID_SUCCESS';

//PROFESSIONALS

export const FETCHING_TYPE_SPECIALTY = 'FETCHING_TYPE_SPECIALTY';
export const FETCH_TYPE_SPECIALTY_SUCCESS = 'FETCH_TYPE_SPECIALTY_SUCCESS';
export const FETCHING_ESPECIALTY = 'FETCHING_ESPECIALTY';
export const FETCH_ESPECIALTY_SUCCESS = 'FETCH_ESPECIALTY_SUCCESS';
export const FETCHING_TOWN = 'FETCHING_TOWN';
export const FETCH_TOWN_SUCCESS = 'FETCH_TOWN_SUCCESS';
export const FETCHING_PROFESSIONAL = 'FETCHING_PROFESSIONAL';
export const FETCH_PROFESSIONAL_SUCCESS = 'FETCH_PROFESSIONAL_SUCCESS';
export const FETCHING_PROFESSIONALS = 'FETCHING_PROFESSIONALS';
export const FETCH_PROFESSIONALS_SUCCESS = 'FETCH_PROFESSIONALS_SUCCESS';
export const FETCHING_MORE_PROFESSIONALS = 'FETCHING_MORE_PROFESSIONALS';
export const FETCH_MORE_PROFESSIONALS_SUCCESS = 'FETCH_MORE_PROFESSIONALS_SUCCESS';
export const FETCHING_MEDICAL_CENTER = 'FETCHING_MEDICAL_CENTER';
export const FETCH_MEDICAL_CENTER_SUCCESS = 'FETCH_MEDICAL_CENTER_SUCCESS';
export const FETCHING_MEDICAL_COORDINATES = 'FETCHING_MEDICAL_COORDINATES';
export const FETCH_MEDICAL_COORDINATES_SUCCESS = 'FETCH_MEDICAL_COORDINATES_SUCCESS';
