const strings = {
    general: {
        error: 'Error',
        info: 'Información',
        from: 'Desde',
        to: 'Hasta',
        no_selection: 'Sin selección',
        app_version: 'v',
        clean: 'Limpiar',
        appName: 'Afiliados.',
        complete_all_fields_error: 'Por favor, complete todos los campos.',
        email_valid_error: 'Por favor, ingrese un mail correcto.',
        password_not_match: 'Las contraseñas no coinciden.',
        invalid_password:
            'Las contraseñas no cumplen con el requisito de seguridad minimo (letras, números y mas de 8 caracteres).',
        updation_needed: 'Actualización Necesaria',
        updation_needed_description: 'Se necesita actualizar la aplicación para poder continuar su uso.',
        go_to_playstore: 'Ir al Store',
        no_data: 'No se encuentra información',
        searching_data: 'Buscando información...',
    },
    header: {
        appointment:'Mis Turnos',
        credential: 'Credencial Virtual',
        token_code: 'Código Token',
        qr_code: 'Código QR',
        validations: 'Mis Atenciones',
        register: 'Registrarse',
        family: 'Familiares',
        coinsurance_charges: 'Resumen de Coseguros',
        filters: 'Filtros',
        discapacity: 'Discapacidad',
        batch_info: 'Información de Módulos',
        trip_info: 'Información de Viajes',
        procedures: 'Trámites',
        new_procedure: 'Nuevo Trámite',
        new_appointment:'Solicitar Turno',
        procedure_detail: 'Detalle de Trámite',
        batches: 'Módulos',
        batch_detail: 'Detalle de Módulo',
        professional_detail: 'Consultorios Médicos',
        professional: 'Buscar por Especialidad',
        prescription_detail: 'Detalle de Receta',
        professional_list: 'Cartilla Prestadores',
        professional_maps: 'Geolocalización Consultorio',
        rating_title: 'Calificar Atención',
        unawareness_title: 'Desconocer Atención',
        preAuthorizations: 'Pre-Autorizaciones',
        preAuthorizationDetail: 'Detalle Pre-Autorización',
        newAppointment:'Solicitar Turno'
    },
    beneficiaryInformation: {
        beneficiary_info: 'Información General',
        credential: 'Credencial Virtual',
        no_charges: '-',
        plan: 'Plan',
        plan_prefix: 'PLAN',
        relationship_prefix: 'CONDICIÓN',
        beneficiary_status: 'Estado',
        relationship: 'Parentesco',
        category: 'CATEGORIA',
        attention_code: 'Código de Atención',
        charge_type_prefix: 'TIPO',
        charge_acum_prefix: 'COSEGUROS',
        beneficiary_plans: 'Planes del Afiliado',
    },
    codeGenerator: {
        web_code: 'CODIGO WEB',
        qr_code: 'CODIGO QR',
        generate_another: 'Generar Nuevo',
        qr_message: 'Provea el siguiente código QR a su prestador antes de realizarse la atención médica.',
        token_message:
            'Provea el siguiente código Token a su prestador antes de realizarse la atención médica.',
        generating_qr_code: 'Generando Código QR...',
        expiration: 'Expira',
        expiration_in: 'Este código expirará en',
        qr_hour_message: 'Es importante que la hora de su dispositivo este correctamente configurada',
    },
    drawer: {
        log_out: 'Cerrar Sesión',
        opt1: 'Familiares',
        not_supported:
            'No ha sido posible establecer comunicación con el CallCenter desde la Aplicación. Realice la llamada de manera manual al siguiente numero:',
        opt2: 'Llamar al Contact-Center',
        opt3: 'Trámites',
        opt4: 'Turnos',
        opt5: 'Módulos',
        opt6: 'Pre-Autorizaciones',
        opt7: 'Prestadores',

    },
    errorBoundary: {
        error_ocurred:
            'Ha ocurrido un error inesperado. Verifique su Conexion a Internet e intente nuevamente.',
    },
    familyManagement: {
        available_users: 'Grupo Familiar',
        loadingFamily: 'Cargando Familiares...',
    },
    login: {
        user: 'Usuario',
        password: 'Contraseña',
        log_in: 'Ingresar',
        create_account: 'Registrarse',
        complete_all_fields_error: 'Por favor, complete usuario y contraseña.',
        verify_account: 'Ingresar código para validar cuenta',
        forgot_password: '¿Olvidó su contraseña?',
        email_verification_required: 'Por favor, verifique su cuenta con el mail que le hemos enviado.',
        account_created: 'Cuenta creada con éxito. Le hemos enviado un mail para que verifique su cuenta.',
    },
    renewPassword: {
        change_password: 'Se requiere un cambio de contraseña para confirmar su cuenta.',
        new_password: 'Nueva contraseña',
        new_password_again: 'Re-escriba contraseña',
        password_requirements: 'La contraseña debe contener letras, números y más de 8 caracteres.',
        update_password_success: 'La contraseña fue actualizada con éxito',
    },
    forgotPassword: {
        email_success_message_title: 'Envío de email exitoso',
        email_success_message_info:
            'Se ha enviado a un email a su casilla de correo con el código que debe ingresar a continuación',
        otp_code: 'Código',
        forgot_password_success_title: 'Cambio de Contraseña exitoso',
        forgot_password_success_info: 'Se ha cambiado su contraseña de manera exitosa',
    },
    signUp: {
        beneficiary_number: 'Número de afiliado (con - y /)',
        id_type: 'Tipo de documento',
        id_number: 'Documento de identidad',
        date_of_birth: 'Fecha de nacimiento',
        email: 'Email',
        end: 'Finalizar',
        validating_data: 'Validando Datos...',
        creating_account: 'Creando su cuenta...',
        next: 'Siguiente',
        behind: 'Atrás',
    },
    tabBar: {
        credential: 'Credencial',
        my_attentions: 'Mis Atenciones',
        coinsurance_values: 'Coseguros',
        discapcity: 'Discapacidad',
        batches: 'Módulos',
        procedures: 'Trámites',
    },
    validations: {
        no_validations: 'El afiliado seleccionado no posee atenciones.',
        detail: 'Detalle',
        date: 'FECHA',
        date_time: 'FECHA Y HORA',
        medical_center: 'CENTRO MEDICO',
        validation_type: 'TIPO DE VALIDACION',
        validations: 'PRACTICAS VALIDADAS',
        total_coinsuance_value: 'COSEGURO',
        loading_validations: 'Cargando Atenciones...',
    },
    validationItem: {
        status: 'ESTADO',
    },
    coinsurance_charges: {
        no_coinsurance_charges_found: 'El afiliado seleccionado no posee pagos de coseguros.',
    },
    verificationCode: {
        complete_all_digits: 'Debe completar todos los dígitos.',
        complete_code: 'Ingrese el código de confimación enviado a su email.',
    },
    common: {
        title: 'VEM',
        pre_title: 'IPROSS',
        title_detail: 'Validación Electrónica Móvil',
        confirm: 'Confirmar',
        cancel: 'Cancelar',
        user: 'Usuario',
        password: 'Contraseña',
        password_again: 'Repita Contraseña',
        loading: 'Cargando...',
    },
    errors: {
        required: 'Campo Requerido',
        email_not_valid: 'Email no válido',
        passwords_must_match: 'Las contraseñas no coinciden',
        invalid_beneficiary_code: 'Código de Beneficiario Inválido',
    },
    filters: {
        apply: 'Aplicar Filtros',
        save: 'Guardar',
    },
    validationStatus: {
        practitioner: 'Médico',
        beneficiary: 'Afiliado',
        general_status: 'Estado General',
        status: 'Estado',
        quantity: 'Cantidad',
        unit_price: 'Precio unitario de coseguros',
        subtotal: 'Subtotal de coseguros',
        refundable: 'Reintegrable',
        resolution: 'Resolución',
        charge_total: 'Total de Coseguros',
        rate_validation: 'Calificar Atención',
        disclaim_validation: 'Desconocer Atención',
    },
    fileUploader: {
        no_files_uploaded: 'No hay archivos cargados',
        files: 'Archivos',
        upload_file: 'Subir Archivo',
    },
    batches: {
        loading_batches: 'Cargando Módulos...',
        no_batches: 'El afiliado seleccionado no posee módulos.',
        loading_batch: 'Cargando Módulo...',
    },
    batchItem: {
        from: 'Desde',
        to: 'Hasta',
    },
    batchDetail: {
        no_items_assigned: 'No hay ítems asociados al módulo',
        loading_items: 'Cargando ítems...',
    },
    activeBatchItem: {
        status: 'Estado',
        from: 'Desde',
        to: 'Hasta',
        active_batch: 'Módulo Activo',
    },
    newProcedure: {
        procedure_creation_success: 'El Trámite se ha creado de manera exitosa',
    },
    procedureForm: {
        beneficiary: 'Afiliado',
        procedure_type: 'Tipo de Trámite',
        certificate_type: 'Tipo de Certificado',
        description: 'Descripción',
        add_image: 'Adjuntar Imagen',
    },
    professionalForm: {
        specialty_type: 'Tipo Especialidad',
        specialty: 'Especialidad',
        certificate_type: 'Tipo de Certificado',
        description: 'Descripción',
        city: 'Localidad / Ciudad',
        search: 'Consultar',
    },

    procedureDetail: {
        procedure_update_success: 'El Trámite se ha editado de manera exitosa',
        procedure_id: 'Trámite N°',
    },
    procedureMessages: {
        placeholder: 'Escriba un mensaje...',
        there_arent_messages: 'No hay mensajes',
    },
    closedProcedures: {
        no_procedures: 'No se encontraron trámites',
    },
    closedProcedureItem: {
        procedure: 'Trámite N°',
        date: 'FECHA',
        status: 'ESTADO',
    },
    openedProcedures: {
        no_procedures: 'No se encontraron trámites abiertos',
    },
    openedProcedure: {
        procedure: 'Trámite N°',
        date: 'Creado',
        status: 'Estado',
        beneficiary: 'Afiliado',
        procedure_type: 'Tipo de Trámite',
    },
    openedAppointments: {
        fecha: 'Fecha Turno',
        delegation:'Delegación',
        sector: 'Sector',
        id: 'Turno N°',
        hora: 'Horario',
        delegation_address:'Dirección',
        status:'Estado',
        turno:'Turnos Disponibles',
        no_appointments: 'No se encontraron Turnos Pendientes',
        attendance_description: 'Estado Atención',
        cancel: 'Cancelar Turno',
        status_general:'Estado General del Turno',
    },
    
    newAppointment: {
        appointment_creation_success: 'El Turno se ha generado de manera exitosa',
    },

    prescriptionList: {
        date: 'Fecha',
        status: 'Estado',
        no_prescriptions: 'El afiliado seleccionado no posee recetas.',
        loading_prescriptions: 'Cargando Recetas...',
    },
    prescriptionDetail: {
        prescription: 'Receta N°',
        diagnosis: 'Diagnóstico',
        dosis_quantity: 'Dosis Diria',
        medicine: 'Medicamento',
        treatment_days: 'Días de Tratamiento',
        practitioner: 'Médico',
        beneficiary: 'Afiliado',
        general_status: 'Estado General',
        created_date: 'Fecha',
        prescriptions: 'Detalle',
        prescription_number: 'Números de Autorización',
        observations: 'Indicaciones',
        package_quantity: 'Cantidad de Envases',
        is_preauthorized: 'Receta Preautorizada',
    },
    authorizationRanking: {
        rating_successfully_saved: 'Su calificación se ha guardado exitosamente',
        attention_quality: 'Calidad de Atención',
        attention_duration: 'Duración de Atención',
        wait_time: 'Tiempo de Espera',
        additional_payed: '¿Se cobró adicional?',
        rating: 'Calificación',
    },
    authorizationUnawareness: {
        there_is_already_a_procedure: 'Ya hay un tŕamite creado para ésta validación.',
        procedure_creation_successul_message: 'Su trámite ha sido creado exitosamente',
        unawareness_description:
            'Usted está a punto de desconocer la atención. Dicha operación generará un nuevo trámite, el cuál será revisado por el instituto y podrá ser consultado en la sección de "Trámites"',
        authorization_to_cancel: 'Validación a Desconocer',
        nro_authorization: 'N° de Validación',
        practitioner: 'Médico',
        medical_center: 'Consultorio',
        description: 'Descripción',
        see_procedure: 'Ver Trámite',
    },
    preAuthorizationList: {
        expiration: 'Vence',
    },
    preAuthorizationDetail: {
        generalStatus: 'Estado General',
        manualCode: 'Código Manual',
        quantity: 'Cantidad',
        available: 'Disponibles',
        coInsurance: 'Coseguro',
        coverage: 'Aplica Cobertura',
    },
};

export default strings;
