#Datasource
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?reWriteBatchedInserts=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.initialization-mode=never
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=70
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=900000
#JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
#Server Properties
server.servlet.context-path=/identity-service/v1
server.port=${PORT}
server.forward-headers-strategy=framework
#Logging
logging.level.com.capacidad.identityservice=warn
logging.file.name=/shared/logs/identity-service-api.log
#i18n
spring.messages.basename=messages/messages
spring.messages.fallback-to-system-locale=false
spring.messages.encoding=UTF-8
spring.mvc.locale-resolver=accept_header
spring.mvc.locale=es
#Actuator
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=metrics,health,info,httptrace,env,sessions
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.httptrace.enabled=true
management.endpoint.env.enabled=true
management.endpoint.sessions.enabled=true
management.health.redis.enabled=false
#Mailing
spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=${SMTP_PORT}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
com.capacidad.identityservice.mail.from=notificaciones@ipross.rionegro.gov.ar
#Custom
com.capacidad.identityservice.identifier=qkUbIAF2U4HNUVU7syFbcQFOTVSXuE
com.capacidad.identityservice.account.verification-window-minutes=60
com.capacidad.identityservice.account.verification-retry-minutes=15
com.capacidad.identityservice.account.issuer=https://app.vemsalud.com/identity-service/v1
#Flyway
spring.flyway.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.flyway.schemas=public
spring.flyway.user=${DATABASE_USERNAME}
spring.flyway.password=${DATABASE_PASSWORD}
spring.flyway.locations=classpath:migrations/${spring.profiles.active}
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true
#spring.flyway.baseline-version=1.1.3
#Redis
spring.redis.cluster.nodes=${REDIS_NODES}
spring.redis.cluster.max-redirects=3
spring.redis.lettuce.pool.min-idle=50
spring.redis.lettuce.pool.max-idle=150
spring.redis.lettuce.pool.max-active=350
spring.redis.lettuce.pool.max-wait=5000
spring.redis.timeout=3500ms