INSERT INTO application_role (id, name, access_level, resource_id_required, reusable_resource_id)
VALUES (1, 'BENEFICIARY', 1, true, false),
       (2, 'PRACTITIONER', 1, true, false),
       (3, 'MEDICAL_CENTER', 1, true, true),
       (4, 'FUNDER', 9, false, true),
       (5, 'ADMIN', 10, false, true),
       (6, 'ORGANIZATION', 1, true, true),
       (7, 'CLIENT', 1, false, true),
       (8, 'AUDITOR', 1, false, true)
ON CONFLICT DO NOTHING;

INSERT INTO application_state (id, name)
VALUES (1, 'CONFIRMED'),
       (2, 'UNCONFIRMED'),
       (3, 'DISABLED')
ON CONFLICT DO NOTHING;

INSERT INTO application_resource (id, name)
VALUES (1, 'beneficiaries'),
       (2, 'practitioners'),
       (3, 'medical_authorizations'),
       (4, 'medical_coverages'),
       (5, 'contracts'),
       (6, 'organizations'),
       (7, 'medical_centers'),
       (8, 'settlements'),
       (9, 'users'),
       (10, 'regions'),
       (11, 'nomenclators'),
       (12, 'categories'),
       (13, 'companies'),
       (14, 'insurance_plans'),
       (15, 'reports'),
       (20, 'expiration'),
       (23, 'rules'),
       (24, 'files'),
       (25, 'audit_trays'),
       (26, 'audit_tray'),
       (27, 'practitioner_budgets'),
       (28, 'batches'),
       (29, 'beneficiary_budgets'),
       (30, 'notifications'),
       (31, 'devices'),
       (32, 'procedures'),
       (33, 'properties'),
       (34, 'pre_authorizations'),
       (35, 'prescriptions'),
       (36, 'medicines'),
       (37, 'practitioner'),
       (38, 'beneficiary'),
       (39, 'medical_authorization_items'),
       (40, 'audit_history'),
       (41, 'prescription_restrictions'),
       (42, 'topics'),
       (43, 'calendar'),
       (44, 'trade_unions'),
       (45, 'permission_groups')
ON CONFLICT DO NOTHING;

INSERT INTO application_permission_group (id, name)
VALUES --beneficiaries
       (1, 'Alta, Baja, Modificacion, Consulta de Afiliados'),
       (2, 'Consulta de Afiliados'),
       --practitioners
       (3, 'Alta, Baja, Modificacion, Consulta de Prestadores'),
       (4, 'Consulta de Prestadores'),
       --medical_authorizations
       (5, 'Modificacion, Consulta de Validaciones'),
       (6, 'Alta, Modificacion, Consulta de Validaciones'),
       (7, 'Consulta de Validaciones'),
       --medical_coverages
       (8, 'Alta, Baja, Modificacion, Consulta de Coberturas'),
       (9, 'Consulta de Coberturas'),
       --contracts,
       (10, 'Alta, Baja, Modificacion, Consulta de Convenios'),
       (11, 'Consulta de Convenios'),
       --organizations,
       (12, 'Alta, Baja, Modificacion, Consulta de Asociaciones'),
       (13, 'Consulta de Asociaciones'),
       --medical_centers
       (14, 'Alta, Baja, Modificacion, Consulta de Centros Medicos'),
       (15, 'Consulta de Centros Medicos'),
       --settlements,
       (16, 'Alta, Baja, Modificacion, Consulta de Liquidaciones'),
       (17, 'Alta, Modificacion, Consulta de Liquidaciones'),
       (18, 'Modificacion y Consulta de Liquidaciones'),
       (19, 'Consulta de Liquidaciones'),
       --users
       (20, 'Alta, Baja, Modificacion, Consulta de Usuarios'),
       (21, 'Alta, Baja, Consulta de Usuarios'),
       --regions
       (22, 'Alta, Baja, Modificacion, Consulta de Regiones'),
       (23, 'Consulta de Regiones'),
       --nomenclators
       (24, 'Alta, Baja, Modificacion, Consulta de Nomenclador'),
       (25, 'Consulta de Nomenclador'),
       --categories
       (26, 'Alta, Baja, Modificacion, Consulta de Categorias'),
       (27, 'Consulta de Categorias'),
       --companies
       (28, 'Alta, Baja, Modificacion, Consulta de Empresas/Organismos'),
       (29, 'Consulta de Empresas/Organismos'),
       --insurance_plans
       (30, 'Alta, Baja, Modificacion, Consulta de Planes'),
       (31, 'Consulta de Planes'),
       --reports
       (32, 'Consulta de Tablero'),
       --rules
       (33, 'Alta, Baja, Modificacion, Consulta de Reglas'),
       (34, 'Consulta de Reglas'),
       --files
       (35, 'Alta, Baja, Modificacion, Consulta de Archivos'),
       (36, 'Consulta de Archivos'),
       --audit_trays
       (37, 'Alta, Baja, Modificacion, Consulta de Bandejas'),
       (38, 'Consulta de Bandejas'),
       --audit_tray
       (39, 'Conexion a Bandejas'),
       --practitioner_budgets
       (40, 'Modificacion y Consulta de Consumo de Coseguros Voluntarios del Prestador'),
       (41, 'Consulta de Consumo de Coseguros Voluntarios del Prestador'),
       --batches
       (42, 'Alta, Baja, Modificacion, Consulta de Modulos'),
       (43, 'Consulta de Modulos'),
       --beneficiary_budgets
       (44, 'Alta, Baja, Modificacion, Consulta de Consumo de Coseguros R.S del Afiliado'),
       (45, 'Consulta de Consumo de Coseguros R.S del Afiliado'),
       --notifications
       (46, 'Modificacion y Consulta de Notificaciones'),
       --devices
       (47, 'Alta y Modificacion de Dispositivo en uso (apps)'),
       --procedures
       (48, 'Alta, Modificacion y Consulta de Tramites'),
       (49, 'Alta y Consulta de Tramites'),
       (50, 'Consulta de Tramites'),
       --properties
       (51, 'Modificacion y Consulta de Propiedades de Financiador'),
       --pre_authorizations
       (52, 'Alta, Modificacion y Consulta de Preautorizaciones/Homoclaves'),
       (53, 'Consulta de Preautorizaciones/Homoclaves'),
       --prescriptions
       (54, 'Modificacion, Consulta de Recetas'),
       (55, 'Alta, Modificacion, Consulta de Recetas'),
       (56, 'Consulta de Recetas'),
       --medicines
       (57, 'Consulta de Medicamentos'),
       --medical_authorization_items
       (58, 'Consulta de Items de Validacion'),
       --audit_history
       (59, 'Modificacion y Consulta de Validacion Auditoria (Objetos del Auditor'),
       --prescription_restrictions
       (60, 'Alta, Baja, Modificacion, Consulta de Restricciones de Receta'),
       (61, 'Consulta de Restricciones de Receta'),
       --topics
       (62, 'Alta, Baja, Modificacion, Consulta de Topicos'),
       --expiration
       (63, 'Alta, Baja, Modificacion, Consulta de Vencimientos Afiliado'),
       (64, 'Consulta de Vencimientos Afiliado'),
       --calendar
       (65, 'Alta, Baja, Modificacion, Consulta de Calendario'),
       --trade_unions
       (66, 'Alta, Baja, Modificacion, Consulta de Gremios y Coberturas'),
       (67, 'Consulta de Grupos de Permisos'),
       --CUSTOM PERMS
       (68, 'Registro de Usuarios Afiliado'),
       (69, 'Baja y Modificacion de Afiliados'),
       (70, 'Consulta de Tablero Recetas'),
       (71, 'Notificaciones Push'),
       (72, 'Importaciones')
       ON CONFLICT DO NOTHING;

-- resource_operations_key = resource_id
INSERT INTO permission_group_resource_operations(permission_group_id,resource, resource_operations)
VALUES (1, 'beneficiaries', 'all'),
       (2, 'beneficiaries', 'read'),
       (3, 'practitioners', 'all'),
       (4, 'practitioners', 'read'),
       (5, 'medical_authorizations','read,update'),
       (6, 'medical_authorizations','read,update,create'),
       (7, 'medical_authorizations','read'),
       (8, 'medical_coverages', 'all'),
       (9, 'medical_coverages', 'read'),
       (10, 'contracts', 'all'),
       (11, 'contracts', 'read'),
       (12, 'organizations', 'all'),
       (13, 'organizations', 'read'),
       (14, 'medical_centers', 'all'),
       (15, 'medical_centers', 'read'),
       (16, 'settlements', 'all'),
       (17, 'settlements', 'read,create,update'),
       (18, 'settlements', 'read,update'),
       (19, 'settlements', 'read'),
       (20, 'users', 'all'),
       (21, 'users', 'read,create,delete'),
       (22, 'regions', 'all'),
       (23, 'regions', 'read'),
       (24, 'nomenclators', 'all'),
       (25, 'nomenclators', 'read'),
       (26, 'categories', 'all'),
       (27, 'categories', 'read'),
       (28, 'companies', 'all'),
       (29, 'companies', 'read'),
       (30, 'insurance_plans', 'all'),
       (31, 'insurance_plans', 'read'),
       (32, 'reports', 'read'),
       (33, 'rules', 'all'),
       (34, 'rules', 'read'),
       (35, 'files', 'all'),
       (36, 'files', 'read'),
       (37, 'audit_trays', 'all'),
       (38, 'audit_trays', 'read'),
       (39, 'audit_tray', 'read'),
       (40, 'practitioner_budgets', 'read,update'),
       (41, 'practitioner_budgets', 'read'),
       (42, 'batches', 'all'),
       (43, 'batches', 'read'),
       (44, 'beneficiary_budgets', 'all'),
       (45, 'beneficiary_budgets', 'read'),
       (46, 'notifications', 'read,update'),
       (47, 'devices', 'create,update'),
       (48, 'procedures', 'read,create,update'),
       (49, 'procedures', 'read,create'),
       (50, 'procedures', 'read'),
       (51, 'properties', 'read,update'),
       (52, 'pre_authorizations', 'read,create,update'),
       (53, 'pre_authorizations', 'read'),
       (54, 'prescriptions', 'read,update'),
       (55, 'prescriptions', 'read,create,update'),
       (56, 'prescriptions', 'read'),
       (57, 'medicines', 'read'),
       (58, 'medical_authorization_items', 'read'),
       (59, 'audit_history', 'read,update'),
       (60, 'prescription_restrictions', 'all'),
       (61, 'prescription_restrictions', 'read'),
       (62, 'topics', 'all'),
       (63, 'expiration', 'all'),
       (64, 'expiration', 'read'),
       (65, 'calendar', 'all'),
       (66, 'trade_unions', 'all'),
       (67, 'permission_groups', 'read'),
       (68, 'beneficiary_users', 'create,delete,update'),
       (69, 'beneficiaries', 'update,delete'),
       (70, 'report_prescriptions', 'read'),
       (71, 'notifications_push', 'create'),
       (72, 'imports', 'create')
ON CONFLICT DO NOTHING;

-- BENEFICIARY = 1
-- PRACTITIONER = 2
-- MEDICAL CENTER = 3
-- FUNDER = 4
-- ADMIN = 5
-- ORGANIZATION = 6
-- AUDITOR  = 8
INSERT INTO application_role_permission_group(application_role_id, application_permission_group_id)
VALUES --beneficiaries
       (5, 1),
       (4, 1),
       (1, 2),
       (2, 2),
       (3, 2),
       (6, 2),
       (8, 2),
       --practitioners
       (5, 3),
       (4, 3),
       (2, 4),
       (1, 4),
       (3, 4),
       (7, 4),
       (6, 4),
       (8, 4),
       --medical_authorizations
       (5, 5),
       (4, 5),
       (1, 7),
       (2, 6),
       (3, 6),
       (6, 7),
       (8, 5),
       --medical_coverages
       (5, 8),
       (4, 8),
       (6, 9),
       (8, 9),
       --contracts,
       (5, 10),
       (4, 10),
       (2, 11),
       (3, 11),
       (6, 11),
       (8, 11),
       --organizations,
       (5, 12),
       (4, 12),
       (6, 13),
       --medical_centers
       (5, 14),
       (4, 14),
       (1, 15),
       (6, 15),
       --settlements
       (5, 16),
       (4, 17),
       (2, 18),
       (3, 18),
       (6, 18),
       --users,
       (5, 20),
       (4, 20),
       (3, 21),
       (6, 21),
       --regions
       (5, 22),
       (4, 22),
       (1, 23),
       (8, 23),
       (6, 23),
       --nomenclators
       (5, 24),
       (4, 24),
       (2, 25),
       (3, 25),
       (6, 25),
       (8, 25),
       --categories
       (5, 26),
       (4, 26),
       --companies
       (5, 28),
       (4, 28),
       --insurance_plans
       (5, 30),
       (4, 30),
       (6, 31),
       (8, 31),
       --reports
       (5, 32),
       (4, 32),
       (1, 32),
       (2, 32),
       (3, 32),
       (6, 32),
        --rules
       (5, 33),
       (4, 33),
       --files
       (5, 35),
       (4, 35),
       (1, 36),
       (2, 35),
       (3, 35),
       (6, 36),
       (8, 36),
       --audit_trays
       (5, 37),
       (4, 37),
       --audit_tray
       (8, 38),
       (8, 39),
       --practitioner_budgets
       (3, 40),
       (2, 41),
       --batches
       (5, 42),
       (4, 42),
       (8, 42),
       (1, 43),
       --beneficiary_budgets
       (5, 44),
       (4, 44),
       (1, 45),
       (8, 45),
       --notifications
       (5, 46),
       (4, 46),
       (1, 46),
       (2, 46),
       (3, 46),
       (6, 46),
       (8, 46),
       --devices
       (1, 47),
       (2, 47),
       (3, 47),
       --procedures
       (5, 48),
       (4, 48),
       (1, 49),
       (8, 50),
       --properties
       (5, 51),
       (4, 51),
       --pre_authorizations
       (5, 52),
       (4, 52),
       (1, 53),
       (2, 53),
       (3, 53),
       --prescriptions
       (5, 54),
       (4, 54),
       (1, 56),
       (2, 55),
       (3, 55),
       (8, 56),
       --medicines
       (5, 57),
       (4, 57),
       (2, 57),
       (3, 57),
       (8, 57),
       --medical_authorization_items
       (5, 58),
       (4, 58),
       (2, 58),
       (3, 58),
       (6, 58),
       (8, 58),
       --audit_history
       (8, 59),
       --prescription_restrictions
       (5, 60),
       (4, 60),
       (8, 61),
       --topics
       (5, 62),
       --expiration
       (5, 63),
       (4, 63),
       (8, 64),
       --calendar
       (5, 65),
       (4, 65),
       --calendar
       (5, 66),
       (4, 66),
       --permission_groups
       (5, 67),
       (4, 67),
       --imports
       (5, 72),
       --notifications_push
       (5, 71)
ON CONFLICT DO NOTHING;

INSERT INTO application_permission_suggestion (id, name, application_role_id, description)
VALUES (1, 'Directivos', 4, 'Gestion de Afiliados, Planes y Convenios. ' ||
                            'Visualizacion de Modulos, Validaciones, Liquidaciones, Tramites, Recetas, Prestadores, Entidades, Tableros y Configuraciones ' ||
                            '(Planes, Nomenclador, Convenios y Auditoria)'),
       (2, 'Delegados y Sub Delegados', 4, 'Gestion de Afiliados y Homoclaves. ' ||
                                           'Visualizacion de Modulos, Validaciones, Tramites, Recetas, Prestadores y Configuraciones (Planes, Nomenclador, Convenios)'),
       (3, 'CAT', 4, 'Consulta, Usuarios y Edicion de Afiliados. Gestion de Homoclaves. ' ||
                  'Visualizacion de Modulos, Validaciones, Tramites, Recetas, Prestadores y Configuraciones (Planes, Nomenclador, Convenios)'),
       (4, 'Administrativo Delegacion', 4, 'Consulta, Usuarios y Edicion de Afiliados. Gestion de Homoclaves. Resolucion de Tramites ' ||
                         'Visualizacion de Modulos, Validaciones, Tramites, Recetas, Prestadores y Configuraciones (Planes, Nomenclador, Convenios)'),
       (5, 'Auditor Facturacion', 4, 'Visualizacion de Modulos, Validaciones, Liquidaciones, Recetas, Afiliados, Prestadores y Configuraciones (Planes, Nomenclador, Convenios)'),
       (6, 'Auditor Farmacia', 4, 'Visualizacion de Recetas, Afiliados, Prestadores, Tablero de Recetas'),
       (7, 'Prensa', 4, 'Visualizacion de Tableros. Notificaciones Push')
ON CONFLICT DO NOTHING;

INSERT INTO application_permission_suggestion_group (application_permission_suggestion_id, application_permission_group_id)
VALUES --Directivos
       (1, 1),
       (1, 8),
       (1, 30),
       (1, 10),
       (1, 43),
       (1, 7),
       (1, 19),
       (1, 50),
       (1, 56),
       (1, 58),
       (1, 4),
       (1, 15),
       (1, 13),
       (1, 29),
       (1, 32),
       (1, 24),
       (1, 37),
       (1, 68),
       (1, 21),
       (1, 46),
       (1, 36),
       (1, 23),
       --Delegados y Sub Delegados
       (2, 1),
       (2, 9),
       (2, 52),
       (2, 43),
       (2, 7),
       (2, 50),
       (2, 56),
       (2, 4),
       (2, 31),
       (2, 25),
       (2, 11),
       (2, 68),
       (2, 21),
       (2, 46),
       (2, 36),
       (2, 23),
       --CAT
       (3, 2),
       (3, 9),
       (3, 68),
       (3, 21),
       (3, 69),
       (3, 52),
       (3, 43),
       (3, 7),
       (3, 50),
       (3, 56),
       (3, 4),
       (3, 31),
       (3, 25),
       (3, 11),
       (3, 46),
       (3, 36),
       --Administrativo Delegacion
       (4, 2),
       (4, 9),
       (4, 68),
       (4, 21),
       (4, 69),
       (4, 52),
       (4, 43),
       (4, 7),
       (4, 48),
       (4, 56),
       (4, 4),
       (4, 31),
       (4, 25),
       (4, 11),
       (4, 46),
       (4, 36),
       --Facturacion
       (5, 2),
       (5, 9),
       (5, 43),
       (5, 7),
       (5, 18),
       (5, 56),
       (5, 4),
       (5, 31),
       (5, 25),
       (5, 11),
       (5, 58),
       (5, 36),
       --Auditor Farmacia
       (6, 2),
       (6, 4),
       (6, 70),
       (6, 56),
       --Prensa
       (7, 32),
       (7, 71),
       (7, 62),
       (7, 46)
ON CONFLICT DO NOTHING;

-- Deprecated
-- INSERT INTO application_scope_role (id, role_id, resource_id, operations)
-- VALUES
-- --      ADMIN
-- (1, 5, 1, 'all'),
-- (2, 5, 2, 'all'),
-- (3, 5, 3, 'read,update'),
-- (4, 5, 4, 'all'),
-- (5, 5, 5, 'all'),
-- (6, 5, 6, 'all'),
-- (7, 5, 7, 'all'),
-- (8, 5, 8, 'all'),
-- (9, 5, 9, 'all'),
-- (10, 5, 10, 'all'),
-- (11, 5, 11, 'all'),
-- (12, 5, 12, 'all'),
-- (13, 5, 13, 'all'),
-- (14, 5, 14, 'all'),
-- (15, 5, 15, 'all'),
-- (19, 5, 20, 'all'),
-- (20, 5, 23, 'all'),
-- (21, 5, 24, 'all'),
-- (22, 5, 25, 'all'),
-- (23, 5, 28, 'all'),
-- (24, 5, 29, 'all'),
-- (25, 5, 30, 'read,update'),
-- (26, 5, 32, 'read,update,create'),
-- (32, 5, 33, 'read,update'),
-- (27, 5, 34, 'read,create,update'),
-- (28, 5, 35, 'read,update'),
-- (29, 5, 36, 'read'),
-- (30, 5, 39, 'read'),
-- (31, 5, 41, 'all'),
-- (33, 5, 42, 'all'),
-- (34, 5, 43, 'all'),
-- (35, 5, 44, 'all'),
-- --      FUNDER
-- (50, 4, 1, 'all'),
-- (51, 4, 2, 'all'),
-- (52, 4, 3, 'read,update'),
-- (53, 4, 4, 'all'),
-- (54, 4, 5, 'all'),
-- (55, 4, 6, 'all'),
-- (56, 4, 7, 'all'),
-- (57, 4, 8, 'read,create,update'),
-- (58, 4, 9, 'all'),
-- (59, 4, 10, 'all'),
-- (60, 4, 11, 'all'),
-- (61, 4, 12, 'all'),
-- (62, 4, 13, 'all'),
-- (63, 4, 14, 'all'),
-- (64, 4, 15, 'all'),
-- (68, 4, 20, 'all'),
-- (69, 4, 23, 'all'),
-- (70, 4, 24, 'all'),
-- (71, 4, 25, 'all'),
-- (72, 4, 28, 'all'),
-- (73, 4, 29, 'all'),
-- (74, 4, 30, 'read,update'),
-- (75, 4, 32, 'read,update,create'),
-- (76, 4, 33, 'read,update'),
-- (77, 4, 34, 'read,create,update'),
-- (78, 4, 35, 'read,update'),
-- (79, 4, 36, 'read'),
-- (80, 4, 39, 'read'),
-- (81, 4, 41, 'all'),
-- (82, 4, 42, 'read,delete,create'),
-- (83, 4, 43, 'all'),
-- (84, 4, 44, 'all'),
-- --     BENEFICIARY
-- (100, 1, 1, 'read'),
-- (101, 1, 3, 'read'),
-- (102, 1, 15, 'read'),
-- (104, 1, 24, 'read'),
-- (105, 1, 28, 'read'),
-- (106, 1, 29, 'read'),
-- (107, 1, 30, 'read,update'),
-- (108, 1, 31, 'create,update'),
-- (109, 1, 32, 'read,create'),
-- (110, 1, 35, 'read'),
-- (111, 1, 34, 'read'),
-- --     PRACTITIONER
-- (130, 2, 2, 'read'),
-- (131, 2, 8, 'read,update'),
-- (132, 2, 3, 'read,create,update'),
-- (133, 2, 15, 'read'),
-- (134, 2, 24, 'all'),
-- (135, 2, 28, 'read'),
-- (136, 2, 27, 'read'),
-- (137, 2, 30, 'read,update'),
-- (138, 2, 35, 'read,create,update'),
-- (139, 2, 1, 'read'),
-- (140, 2, 31, 'create,update'),
-- (141, 2, 34, 'read'),
-- (142, 2, 36, 'read'),
-- (143, 2, 11, 'read'),
-- (144, 2, 5, 'read'),
-- (145, 2, 39, 'read'),
-- (146, 2, 31, 'create,update'),
-- --     MEDICAL CENTERS
-- (160, 3, 2, 'read'),
-- (161, 3, 8, 'read,update'),
-- (162, 3, 3, 'read,create,update'),
-- (163, 3, 9, 'read,create,delete'),
-- (164, 3, 1, 'read'),
-- (165, 3, 11, 'read'),
-- (166, 3, 15, 'read'),
-- (167, 3, 24, 'all'),
-- (168, 3, 27, 'read,update'),
-- (169, 3, 28, 'read'),
-- (170, 3, 30, 'read,update'),
-- (171, 3, 31, 'create,update'),
-- (172, 3, 34, 'read'),
-- (173, 3, 35, 'read,create,update'),
-- (174, 3, 36, 'read'),
-- (175, 3, 5, 'read'),
-- (176, 3, 39, 'read'),
-- (177, 3, 31, 'create,update'),
-- --     ORGANIZATIONS
-- (190, 6, 2, 'read,create,update,delete'),
-- (191, 6, 8, 'read,update'),
-- (192, 6, 3, 'read'),
-- (193, 6, 9, 'read,create,delete'),
-- (194, 6, 1, 'read'),
-- (195, 6, 5, 'read'),
-- (196, 6, 4, 'read'),
-- (198, 6, 15, 'read'),
-- (199, 6, 24, 'read'),
-- (200, 6, 28, 'read'),
-- (201, 6, 30, 'read,update'),
-- (202, 6, 7, 'all'),
-- (203, 6, 10, 'read'),
-- (204, 6, 6, 'read'),
-- (205, 6, 12, 'read'),
-- (206, 6, 37, 'create,read,delete'),
-- (208, 6, 39, 'read'),
-- --        AUDITORS
-- (249, 8, 1, 'read'),
-- (250, 8, 2, 'read'),
-- (251, 8, 3, 'read,update'),
-- (252, 8, 4, 'read'),
-- (253, 8, 5, 'read'),
-- (254, 8, 6, 'read'),
-- (255, 8, 7, 'read'),
-- (256, 8, 8, 'read'),
-- (258, 8, 10, 'read'),
-- (259, 8, 11, 'read'),
-- (260, 8, 12, 'read'),
-- (261, 8, 13, 'read'),
-- (262, 8, 14, 'read'),
-- (263, 8, 15, 'read'),
-- (267, 8, 20, 'read'),
-- (268, 8, 23, 'read'),
-- (269, 8, 24, 'read'),
-- (270, 8, 25, 'read'),
-- (271, 8, 26, 'read'),
-- (272, 8, 28, 'all'),
-- (273, 8, 29, 'read'),
-- (274, 8, 30, 'read,update'),
-- (275, 8, 32, 'read,update,create'),
-- (276, 8, 35, 'read'),
-- (277, 8, 36, 'read'),
-- (278, 8, 34, 'read'),
-- (279, 8, 39, 'read'),
-- (280, 8, 40, 'read,update'),
-- (281, 8, 41, 'read')
-- ON CONFLICT DO NOTHING;